### ISSUE TITLE
[UX] Modify flow: View dashboard

### ISSUE THREAD

**Issue by nadeswal** [awslabs/iot-application#947] opened 2023-07-31 19:27 UTC
**Current state:** Users are directed to an empty "View mode" state, even if they have no content or are creating the dashboard for the first time.
**Proposed solution:**
_**No content//Creating the dashboard for the first time:**_ 
Direct the users to the “edit mode” dashboard 
**NOTE:** Left and right panels should remain closed in the empty state as well as when no widget is added or selected on the canvas.
**_With content:_**
Users are directed to the “View mode” where they will be able to view their saved dashboard and monitor their assets.
They can click on the “Edit” button to make any further changes to the dashboard
NOTE: Left and right panels should remain closed in the empty state as well as when no widget is added or selected on the canvas.

Refer -
Doc - https://quip-amazon.com/5U2EAtnId09B/Centurion-UX-Pre-GA
Design - https://www.figma.com/file/pmsbdMcD7ieVWRFMNxStIi/VoT--AppKit-%26-Centurion?type=design&node-id=348%3A423854&mode=design&t=1zPNBiyI9sH6mezN-1

**Comment by diehbria** [comment] 2023-09-20 20:10
duplicate of https://github.com/awslabs/iot-application/issues/1277

**Closed by diehbria** 2023-09-20 20:10 UTC
Labels: high priority, UX design
